# These are supported funding model platforms

github: rntxbr
patreon: # Replace with 'your-patreon-username' to link your Patreon account
open_collective: # Replace with 'your-collective-name' to link your Open Collective account
ko_fi: # Replace with 'your-kofi-username' to link your Ko-fi account
tidelift: # Replace with 'platform/package-name' to link your Tidelift account
community_bridge: # Replace with 'your-project-name' to link your Community Bridge account
liberapay: # Replace with 'your-username' to link your Liberapay account
issuehunt: # Replace with your IssueHunt username
otechie: # Replace with your Otechie username

