name: Relatório de Bug
description: Relate um bug para nos ajudar a melhorar o cvats
title: "[BUG]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por preencher este relatório de bug! Por favor, forneça o máximo de detalhes possível para nos ajudar a reproduzir e corrigir o problema.

  - type: textarea
    id: bug-description
    attributes:
      label: Descrição do Bug
      description: Uma descrição clara e concisa do que é o bug.
      placeholder: Diga-nos o que deu errado...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Passos para Reproduzir
      description: Passos para reproduzir o comportamento
      placeholder: |
        1. Vá para '...'
        2. Clique em '....'
        3. Role até '....'
        4. Veja o erro
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportamento Esperado
      description: Uma descrição clara e concisa do que você esperava que acontecesse.
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Comportamento Atual
      description: Uma descrição clara e concisa do que realmente aconteceu.
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navegador
      description: Qual navegador você está usando?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Outro (por favor, especifique no contexto adicional)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Sistema Operacional
      description: Qual sistema operacional você está usando?
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Outro
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Versão do Navegador/Dispositivo
      description: Qual versão do seu navegador ou dispositivo você está usando?
      placeholder: ex: Chrome 120.0, Safari 17.1, iOS 16.0

  - type: textarea
    id: screenshots
    attributes:
      label: Capturas de Tela/Vídeos
      description: Se aplicável, adicione capturas de tela ou gravações de tela para ajudar a explicar seu problema.
      placeholder: Arraste e solte ou cole suas imagens aqui...

  - type: textarea
    id: console-logs
    attributes:
      label: Logs do Console (se aplicável)
      description: Se houver erros no console, por favor cole-os aqui.
      render: shell
      placeholder: Cole qualquer saída relevante do console aqui...

  - type: textarea
    id: additional-context
    attributes:
      label: Contexto Adicional
      description: Adicione qualquer outro contexto sobre o problema aqui.

  - type: checkboxes
    id: terms
    attributes:
      label: Lista de Verificação
      description: Por favor, confirme o seguinte
      options:
        - label: Busquei em issues existentes para garantir que não é uma duplicata
          required: true
        - label: Li as diretrizes de contribuição
          required: true
        - label: Estou fornecendo o relatório de bug de boa fé e com o melhor do meu conhecimento
          required: true
