blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/rntxbr/cvats-app/discussions
    about: Please ask and answer questions here
  - name: 📖 Documentation
    url: https://github.com/rntxbr/cvats-app#readme
    about: Check out our documentation for common questions
  - name: 🔒 Security Issue
    url: mailto:renatokhael@gmail.com
    about: Please report security issues privately via email
