blank_issues_enabled: false
contact_links:
  - name: Discussões no GitHub
    url: https://github.com/rntxbr/cvats-app/discussions
    about: Por favor, faça e responda perguntas aqui
  - name: Documentação
    url: https://github.com/rntxbr/cvats-app#readme
    about: Confira nossa documentação para perguntas comuns
  - name: Problema de Segurança
    url: mailto:renatokhael@gmail.com
    about: Por favor, relate problemas de segurança privadamente via email
