name: Solicitação de Funcionalidade
description: Sugira uma nova funcionalidade ou melhoria para o cvats
title: "[FEATURE]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Obrigado por sugerir uma nova funcionalidade! Por favor, forneça o máximo de detalhes possível para nos ajudar a entender sua solicitação.

  - type: textarea
    id: feature-description
    attributes:
      label: Descrição da Funcionalidade
      description: Uma descrição clara e concisa da funcionalidade que você gostaria de ver adicionada.
      placeholder: Que funcionalidade você gostaria de adicionar?
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Declaração do Problema
      description: Que problema esta funcionalidade resolve? Sua solicitação de funcionalidade está relacionada a um problema?
      placeholder: Descreva o problema que você está tentando resolver...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Solução Proposta
      description: Descreva a solução que você gostaria de ver implementada.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Soluções Alternativas
      description: Descreva quaisquer soluções ou funcionalidades alternativas que você considerou.

  - type: dropdown
    id: feature-category
    attributes:
      label: Categoria da Funcionalidade
      description: Qual área do cvats esta funcionalidade afetaria?
      options:
        - Construtor de Currículo
        - Importação de Currículo/Parser PDF
        - Analisador de Currículo
        - UI/UX
        - Performance
        - Acessibilidade
        - Documentação
        - Outro (por favor, especifique)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      description: Quão importante é esta funcionalidade para você?
      options:
        - Baixa - Seria bom ter
        - Média - Melhoraria minha experiência
        - Alta - Impacta significativamente meu fluxo de trabalho
        - Crítica - Isso está me impedindo de usar o cvats efetivamente

  - type: textarea
    id: use-cases
    attributes:
      label: Casos de Uso
      description: Descreva cenários específicos onde esta funcionalidade seria útil.
      placeholder: |
        1. Quando eu preciso...
        2. Nos casos em que...
        3. Para usuários que...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Exemplos
      description: Se você tiver mockups, esboços ou exemplos de outras ferramentas, por favor compartilhe aqui.
      placeholder: Arraste e solte ou cole qualquer mockup, esboço ou imagem de referência...

  - type: checkboxes
    id: terms
    attributes:
      label: Lista de Verificação
      description: Por favor, confirme o seguinte
      options:
        - label: Busquei em issues existentes para garantir que não é uma duplicata
          required: true
        - label: Esta funcionalidade está dentro do escopo do cvats (construtor de currículos otimizado para ATS)
          required: true
        - label: Estou disposto a ajudar a implementar esta funcionalidade se necessário
          required: false
