name: Pergunta
description: Faça uma pergunta sobre o cvats
title: "[QUESTION]: "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Tem uma pergunta sobre o cvats? Estamos aqui para ajudar! Por favor, forneça o máximo de contexto possível.

  - type: textarea
    id: question
    attributes:
      label: Sua Pergunta
      description: O que você gostaria de saber sobre o cvats?
      placeholder: Faça sua pergunta aqui...
    validations:
      required: true

  - type: dropdown
    id: question-type
    attributes:
      label: Tipo de Pergunta
      description: Que tipo de pergunta você está fazendo?
      options:
        - Como usar uma funcionalidade
        - Solução de problemas
        - Melhores práticas
        - Implementação técnica
        - Relacionado a contribuição
        - Consulta geral
        - Outro
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: Forneça qualquer contexto relevante sobre sua pergunta
      placeholder: |
        - O que você está tentando alcançar?
        - O que você já tentou até agora?
        - Qualquer informação relevante de fundo...

  - type: textarea
    id: browser-info
    attributes:
      label: Informações do Navegador e Sistema
      description: Se sua pergunta estiver relacionada a um problema específico, por favor inclua informações sobre seu navegador e sistema.
      placeholder: |
        Navegador: Chrome/Firefox/Safari/etc.
        Versão: (se conhecida)
        SO: Windows/macOS/Linux/etc.

  - type: checkboxes
    id: terms
    attributes:
      label: Lista de Verificação
      description: Por favor, confirme o seguinte
      options:
        - label: Busquei em issues e documentação existentes
          required: true
        - label: Li as diretrizes de contribuição (se contribuindo)
          required: false
